Use mirror repo
Signed-off-by: Frank A. Zdarsky <fzdarsky@redhat.com>

diff --git a/scripts/build b/scripts/build
--- a/scripts/build
+++ b/scripts/build
@@ -1,39 +1,37 @@
 #!/bin/bash
 
 set -e -o pipefail
-#trap 'echo "# $BASH_COMMAND"' DEBUG
+
+title() { echo -e "\E[34m# $1\E[00m"; }
+fatal() { echo -e "\E[31mError: $1\E[00m"; exit 1; }
+
 
 REPOROOT="$(git rev-parse --show-toplevel)"
 DEMOS=$(cd "${REPOROOT}/demos"; find * -maxdepth 1 -type d | xargs)
-BUILD_ARCH=$(uname -i)
 
 DISTRO=$(grep "^ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
-[ "${DISTRO}" == "rhel" ] || fatal "Error: Must run on a RHEL system (have: ${DISTRO})."
 DISTRO_VERSION=$(grep "^VERSION_ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
-[[ "$DISTRO_VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})$ ]] || fatal "Error: Invalid OS version string (have: ${DISTRO_VERSION})"
+[[ "$DISTRO_VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})$ ]] || fatal "Invalid OS version string (have: ${DISTRO_VERSION})"
 DISTRO_VERSION_MAJOR=${BASH_REMATCH[1]}
 DISTRO_VERSION_MINOR=${BASH_REMATCH[2]}
-[ ${DISTRO_VERSION_MAJOR} -eq 8 -a ${DISTRO_VERSION_MINOR} -ge 7 ] || fatal "Error: Must run on RHEL system >= 8.7 and <9.0 (have: ${DISTRO_VERSION}."
+
 
 usage() {
     local error_message="$1"
 
-    if [ -n "$error_message" ]; then
-        echo "ERROR: $error_message"
-        echo
-    fi
-    echo "Usage: $(basename $0) <demoname>"
-    exit 1
+    echo "Usage: $(basename "$0") <demoname>"
+    [ -n "$error_message" ] && fatal "${error_message}"
+    exit 0
 }
 
 if [[ $# -ne 1 || " ${DEMOS} " != *"$1"* ]]; then
     usage "Must specify demo name (one of [${DEMOS}])."
 fi
 
+
 DEMONAME=$1
 DEMODIR="${REPOROOT}/demos/${DEMONAME}"
 BUILDDIR="${REPOROOT}/builds/${DEMONAME}"
-MIRRORDIR="${REPOROOT}/builds/mirror"
 
 PRIMARY_IP=$(ip route get 8.8.8.8 | head -1 | cut -d' ' -f 7)
 
@@ -44,87 +42,25 @@ OSTREE_SERVER_URL=${OSTREE_SERVER_URL:-http://${PRIMARY_IP}:8080}
 OCP_PULL_SECRET_FILE=${OCP_PULL_SECRET_FILE:-$HOME/.pull-secret.json}
 [ ! -s "${OCP_PULL_SECRET_FILE}" ] && usage "Empty or missing pull secret file ${OCP_PULL_SECRET_FILE}"
 
-title() {
-    echo -e "\E[34m# $1\E[00m";
-}
 
-add_local_mirrors() {
-    if [ ! -d "${REPOROOT}/builds/mirror" ]; then
-        echo "WARNING: No local RPM mirror found at ${REPOROOT}/builds/mirror. Trying to continue without."
-    fi
-    for repo in $(find "${REPOROOT}"/builds/mirror/* -maxdepth 0 -type d); do
-        name=$(basename "${repo}")
-        title "Adding source '${name}' to builder"
-        cat <<- EOF > "${MIRRORDIR}/source_${name}.toml"
-id = "${name}"
-name = "${name} repo"
-type = "yum-baseurl"
-url = "file://${MIRRORDIR}/${name}/"
-check_gpg = false
-check_ssl = false
-system = false
-EOF
-        sudo composer-cli sources delete "${name}" 2>/dev/null || true
-        sudo composer-cli sources add "${MIRRORDIR}/source_${name}.toml"
-    done
-}
+# Adds a source repo using the standard osbuild-composer mechanism (.toml file).
+add_repo() {
+    local source=$1
 
-add_extra_repos() {
-    shopt -s nullglob
-    # Add extra repos defined as osbuild-composer sources directly
-    for source in "${DEMODIR}"/source_*.toml; do
-        title "Adding source '${name}' to builder"
-        # osbuild-composer do not correctly handle baseurls with yum ariables
-        # like $basearch, so we need to render these vars beforehand
-        rendered_source=${BUILDDIR}/$(basename "${source}")
-        sed "s|\$basearch|$(uname -i)|g" "${source}" > "${rendered_source}"
+    id="$(grep -Po '^\s?id\s?=\s?"\K[^"]+' "${source}" | head -n 1)"
+    title "Adding source '${id}' to builder"
 
-        id="$(grep -Po '^\s?id\s?=\s?"\K[^"]+' "${source}" | head -n 1)"
-        title "Adding source '${id}' to builder"
-        sudo composer-cli sources delete "${id}" 2>/dev/null || true
-        sudo composer-cli sources add "${rendered_source}"
-    done
+    # This is a workaround for a current osbuild-composer limitation which is that
+    # it does not correctly handle baseurls with yum variables like $basearch,
+    # so we need to render these vars beforehand
+    rendered_source=${BUILDDIR}/$(basename "${source}")
+    sed \
+        -e "s|\$basearch|$(uname -i)|g" \
+        -e "s|\$releasever|${DISTRO_VERSION_MAJOR}|g" \
+        "${source}" > "${rendered_source}"
 
-    # As osbuild-composer sources do not support GPG keys, we add an alternative
-    # path to add repos, which works-around this limitation by adding 3rd-party
-    # repos as system repos.
-    default_repofile="/usr/share/osbuild-composer/repositories/${DISTRO}-${DISTRO_VERSION//\./}.json"
-    override_repofile="/etc/osbuild-composer/repositories/$(basename "${default_repofile}")"
-    working_repofile="${BUILDDIR}/$(basename "${default_repofile}")"
-    cp "${default_repofile}" "${working_repofile}"
-    for source in "${DEMODIR}"/source_*.repo; do
-        name=$(basename "${source}")
-        title "Adding repo '${name}' to system repos"
-
-        baseurl=$(grep -oP "^\s?baseurl\s?=\s?\K.+" "${source}")
-        gpgkeyurl=$(grep -oP "^\s?gpgkey\s?=\s?\K.+" "${source}")
-        gpgcheck=$(grep -oP "^\s?gpgcheck\s?=\s?\K.+" "${source}")
-
-        gpgkey=""
-        check_gpg="false"
-        if [[ "${gpgcheck}" == "1" && ! -z "${gpgkeyurl}" ]]; then
-            gpgkey=$(curl -sL "${gpgkeyurl}")
-            gpgkey=${gpgkey//$'\n'/\\n}
-            check_gpg="true"
-        fi
-
-        for arch in x86_64 aarch64; do
-            baseurl_rendered=${baseurl//\$basearch/${arch}}
-            baseurl_rendered=${baseurl_rendered//\$releasever/${DISTRO_VERSION_MAJOR}}
-            jq ".${arch} += [{ \
-               \"name\": \"${name}\", \
-               \"baseurl\": \"${baseurl_rendered}\", \
-               \"gpgkey\": \"${gpgkey}\", \
-               \"check_gpg\": ${check_gpg} \
-               }]" "${working_repofile}" > "${working_repofile}.tmp"
-            mv "${working_repofile}.tmp" "${working_repofile}"
-        done
-        sudo cp "${working_repofile}" "${override_repofile}"
-    done
-    shopt -u nullglob
-
-    title "Restarting osbuild-composer service"
-    sudo systemctl restart osbuild-composer.service
+    sudo composer-cli sources delete "${id}" 2>/dev/null || true
+    sudo composer-cli sources add "${rendered_source}"
 }
 
 load_blueprint() {
@@ -142,10 +78,10 @@ waitfor_image() {
     local tstart=$(date +%s)
     echo "$(date +'%Y-%m-%d %H:%M:%S') STARTED"
 
-    local status=$(sudo composer-cli compose status | grep ${uuid} | awk '{print $2}')
+    local status=$(sudo composer-cli compose info --json "${uuid}" | jq -r '.body.queue_status')
     while [ "${status}" =  "RUNNING" ]; do
         sleep 10
-        status=$(sudo composer-cli compose status | grep "${uuid}" | awk '{print $2}')
+        status=$(sudo composer-cli compose info --json "${uuid}" | jq -r '.body.queue_status')
         echo -en "$(date +'%Y-%m-%d %H:%M:%S') ${status}\r"
     done
 
@@ -178,6 +114,7 @@ build_image() {
     title "Loading ${blueprint} blueprint v${version}"
     load_blueprint "${blueprint}" "${blueprint_file}"
 
+    ref="${DISTRO}/${DISTRO_VERSION_MAJOR}/$(uname -i)/edge"
     if [ -n "$parent_version" ]; then
         title "Serving ${parent_blueprint} v${parent_version} container locally"
         sudo podman rm -f ostree-server 2>/dev/null || true
@@ -187,10 +124,10 @@ build_image() {
         sudo podman run -d --name=ostree-server -p 8080:8080 "localhost/${parent_blueprint}:${parent_version}"
 
         title "Building ${image_type} for ${blueprint} v${version}, parent ${parent_blueprint} v${parent_version}"
-        buildid=$(sudo composer-cli compose start-ostree --ref "rhel/8/${BUILD_ARCH}/edge" --url http://localhost:8080/repo/ "${blueprint}" "${image_type}" | awk '{print $2}')
+        buildid=$(sudo composer-cli compose start-ostree --json --ref "${ref}" --url http://localhost:8080/repo/ "${blueprint}" "${image_type}" | jq -r '.body.build_id')
     else
         title "Building ${image_type} for ${blueprint} v${version}"
-        buildid=$(sudo composer-cli compose start-ostree --ref "rhel/8/${BUILD_ARCH}/edge" "${blueprint}" "${image_type}" | awk '{print $2}')
+        buildid=$(sudo composer-cli compose start-ostree --json --ref "${ref}" "${blueprint}" "${image_type}" | jq -r '.body.build_id')
     fi
 
     waitfor_image "${buildid}"
@@ -200,14 +137,23 @@ build_image() {
 }
 
 
+# Verify the MicroShift RPMs have been mirrored to disk
+result=$(sudo composer-cli sources list --json | jq '.body.sources | index("microshift-local")')
+[ "${result}" = null ] && fatal "Did not find local mirror of MicroShift RPMs. Did you run ./scripts/mirror-repos ?"
+
+# Change to the demo's build directory
 mkdir -p "${BUILDDIR}"
 pushd "${BUILDDIR}" &>/dev/null
 
-add_local_mirrors
-add_extra_repos
+# Add additional repos required by the specific demo
+shopt -s nullglob
+for repo in "${DEMODIR}"/source_*.toml; do
+    add_repo "${repo}"
+done
+shopt -u nullglob
 
 # Build images from blueprints in alphabetical order of file names.
-# Assumes files are named following the pattern "${SOME_NAME}_v${SOME_VERSION}.toml".
+# Assumes files are named following the pattern "blueprint_v${SOME_VERSION}.toml".
 # Assumes blueprint N is the parent of blueprint N+1.
 parent_version=""
 for blueprint in "${DEMODIR}"/blueprint_*.toml; do
@@ -232,7 +178,7 @@ else
 fi
 
 # Embed the kickstart into the installer ISO if there's no ISO containing it yet
-if [ ! -f "${BUILDDIR}/installer.${BUILD_ARCH}.iso" ]; then
+if [ ! -f "${BUILDDIR}/installer.$(uname -i).iso" ]; then
     title "Embedding kickstart"
     if [ -f "${SSH_PUBLIC_KEY_FILE}" ]; then
         echo "INFO: Using existing SSH public key ${SSH_PUBLIC_KEY_FILE}"
@@ -254,7 +200,7 @@ if [ ! -f "${BUILDDIR}/installer.${BUILD_ARCH}.iso" ]; then
         USER_AUTHORIZED_KEY=$(cat "${SSH_PUBLIC_KEY_FILE}") \
         OCP_PULL_SECRET_CONTENTS=$(cat "${OCP_PULL_SECRET_FILE}" | jq -c) \
         envsubst > "${BUILDDIR}/kickstart.ks"
-    sudo mkksiso kickstart.ks installer-0.0.0-installer.iso ${DEMONAME}-installer.${BUILD_ARCH}.iso
+    sudo mkksiso kickstart.ks installer-0.0.0-installer.iso "${DEMONAME}-installer.$(uname -i).iso"
     sudo chown -R "$(whoami)." "${BUILDDIR}"
 else
     title "Skipping embedding of kickstart"
diff --git a/scripts/configure-builder b/scripts/configure-builder
--- a/scripts/configure-builder
+++ b/scripts/configure-builder
@@ -2,34 +2,40 @@
 
 set -e -o pipefail
 
-title() {
-    echo -e "\E[34m# $1\E[00m";
-}
+title() { echo -e "\E[34m# $1\E[00m"; }
+fatal() { echo -e "\E[31mError: $1\E[00m"; exit 1; }
 
-fatal() {
-    echo -e "\E[31m$1\E[00m";
-    exit 1
-}
 
 DISTRO=$(grep "^ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
-[ "${DISTRO}" == "rhel" ] || fatal "Error: Must run on a RHEL system (have: ${DISTRO})."
 DISTRO_VERSION=$(grep "^VERSION_ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
-[[ "$DISTRO_VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})$ ]] || fatal "Error: Invalid OS version string (have: ${DISTRO_VERSION})"
+[[ "$DISTRO_VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})$ ]] || fatal "Invalid OS version string (have: ${DISTRO_VERSION})"
 DISTRO_VERSION_MAJOR=${BASH_REMATCH[1]}
 DISTRO_VERSION_MINOR=${BASH_REMATCH[2]}
-[ ${DISTRO_VERSION_MAJOR} -eq 8 -a ${DISTRO_VERSION_MINOR} -ge 7 ] || fatal "Error: Must run on RHEL system >= 8.7 and <9.0 (have: ${DISTRO_VERSION}."
 
+
+# Verify we are on a supported distro.
+case "${DISTRO}" in
+    rhel)
+        # Verify we are on a supported version.
+        [ "${DISTRO_VERSION_MAJOR}" -ge 8 ] || fatal "RHEL version must be >= 8.7 (have: ${DISTRO_VERSION})."
+        [ "${DISTRO_VERSION_MINOR}" -ge 7 ] || fatal "RHEL version must be >= 8.7 (have: ${DISTRO_VERSION})."
+        ;;
+
+    *)
+        fatal "\"${DISTRO}\" is not a supported distribution."
+        ;;
+esac
 
 title "Installing experimental 'rpm-ostree' version (with support for embedding containers)"
 # Remove original rpm-ostree packages
-LIST2REMOVE=$(rpm -qa | egrep '^rpm-ostree' || true)
-[ ! -z "${LIST2REMOVE}" ] && sudo dnf remove -y ${LIST2REMOVE}
+LIST2REMOVE=$(rpm -qa | grep -E '^rpm-ostree' || true)
+[ -n "${LIST2REMOVE}" ] && sudo dnf remove -y ${LIST2REMOVE}
 
 # Clean-up the old osbuild jobs and state to avoid incompatibilities between versions
 sudo rm -rf /var/lib/osbuild-composer || true
 sudo rm -rf /var/cache/{osbuild-composer,osbuild-worker} || true
 
-# Install the experimental rpm-ostree packages
+# Add the repo for the experimental rpm-ostree packages (they'll be installed with osbuild)
 sudo wget -P /etc/yum.repos.d https://copr.fedorainfracloud.org/coprs/walters/ostreerhel8/repo/centos-stream-8/walters-ostreerhel8-centos-stream-8.repo
 
 title "Installing ImageBuilder tools"
@@ -43,16 +49,5 @@ sudo systemctl enable osbuild-composer.socket --now
 sudo systemctl enable cockpit.socket --now
 sudo firewall-cmd -q --add-service=cockpit --permanent
 sudo firewall-cmd --reload
-
-# Temporary workaround until the rhocp-4.12-for-rhel-8-$(uname -i)-rpms repo can be used
-title "Configuring 4.12 beta repo"
-sudo tee /etc/yum.repos.d/rhocp-4.12-el8-beta-$(uname -i)-rpms.repo >/dev/null <<EOF
-[rhocp-4.12-el8-beta-$(uname -i)-rpms]
-name=Beta rhocp-4.12 RPMs for RHEL8
-baseurl=https://mirror.openshift.com/pub/openshift-v4/\$basearch/dependencies/rpms/4.12-el8-beta/
-enabled=1
-gpgcheck=0
-skip_if_unavailable=1
-EOF
 
 title "Done"
diff --git a/scripts/mirror-repos b/scripts/mirror-repos
--- a/scripts/mirror-repos
+++ b/scripts/mirror-repos
@@ -2,74 +2,110 @@
 
 set -e -o pipefail
 
+title() { echo -e "\E[34m# $1\E[00m"; }
+fatal() { echo -e "\E[31mError: $1\E[00m"; exit 1; }
+
+
+MICROSHIFT_VERSION="${MICROSHIFT_VERSION:-4.12}"
+MICROSHIFT_BETA="${MICROSHIFT_BETA:-true}"
+
 REPOROOT="$(git rev-parse --show-toplevel)"
-MIRRORDIR="${REPOROOT}/builds/mirror"
-BUILD_ARCH=$(uname -i)
+MIRROR_DIR="/var/repos/microshift-local"
+MICROSHIFT_RPM_DIR="${REPOROOT}/builds/rpms"
 
-usage() {
-    local error_message="$1"
-
-    if [ -n "$error_message" ]; then
-        echo "ERROR: $error_message"
-        echo
-    fi
-
-    echo "Usage: $(basename $0) <path_or_url_to_MicroShift_RPMs>"
-    exit 1
-}
-
-title() {
-    echo -e "\E[34m# $1\E[00m";
-}
-
-if [ $# -ne 1 ] ; then
-    usage "Missing path or URL to MicroSHift RPMs."
-fi
-MICROSHIFT_RPM_SOURCE=$(realpath $1)
+DISTRO=$(grep "^ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
+DISTRO_VERSION=$(grep "^VERSION_ID=" /etc/os-release | cut -d'=' -f2 | tr -d '"')
+[[ "$DISTRO_VERSION" =~ ^([0-9]{1,})\.([0-9]{1,})$ ]] || fatal "Invalid OS version string (have: ${DISTRO_VERSION})"
+DISTRO_VERSION_MAJOR=${BASH_REMATCH[1]}
+DISTRO_VERSION_MINOR=${BASH_REMATCH[2]}
 
 
-mkdir -p "${MIRRORDIR}"
-pushd "${MIRRORDIR}" &>/dev/null
+# Verify we are on a supported distro.
+case "${DISTRO}" in
+    rhel)
+        # Verify we are on a supported version.
+        [ "${DISTRO_VERSION_MAJOR}" -ge 8 ] || fatal "RHEL version must be >= 8.7 (have: ${DISTRO_VERSION})."
+        [ "${DISTRO_VERSION_MINOR}" -ge 7 ] || fatal "RHEL version must be >= 8.7 (have: ${DISTRO_VERSION})."
+        ;;
 
-title "Downloading MicroShift RPMs"
-# Copy MicroShift RPM packages
-rm -rf microshift-local 2>/dev/null || true
-if [[ "${MICROSHIFT_RPM_SOURCE}" == http* ]] ; then
-    wget -q -nd -r -L -P microshift-local -A rpm "${MICROSHIFT_RPM_SOURCE}"
-else
-    cp -TR "${MICROSHIFT_RPM_SOURCE}" microshift-local
-fi
-# Exit if no RPM packages were found
-if [ $(find microshift-local -name '*.rpm' | wc -l) -eq 0 ] ; then
-    echo "No RPM packages were found at '${MICROSHIFT_RPM_SOURCE}'. Exiting..."
-    exit 1
-fi
-title "Creating local MicroShift repo"
-createrepo microshift-local >/dev/null
+    *)
+        fatal "\"${DISTRO}\" is not a supported distribution."
+        ;;
+esac
 
-title "Mirror OpenShift repo"
-# Download openshift local RPM packages (noarch for python and selinux packages)
-rm -rf openshift-local 2>/dev/null || true
-reposync -n -a ${BUILD_ARCH} -a noarch --download-path openshift-local \
-            --repo=fast-datapath-for-rhel-8-${BUILD_ARCH}-rpms \
-            --repo=rhocp-4.12-el8-beta-${BUILD_ARCH}-rpms \
-            >/dev/null
+# Create an empty mirror repo dir.
+sudo rm -rf "${MIRROR_DIR}" 2>/dev/null && sudo mkdir -p "${MIRROR_DIR}"
+
+# Configure the right repos for this distro, version, and release channel
+repos=""
+case "${DISTRO}" in
+    rhel)
+        # Configure MicroShift release or beta repos.
+        if [ "${MICROSHIFT_BETA}" = true ]; then
+            microshift_repo="rhocp-${MICROSHIFT_VERSION}-beta-for-rhel-${DISTRO_VERSION_MAJOR}-$(uname -i)-rpms"
+            title "Configuring ${microshift_repo} repo"
+            sudo subscription-manager repos --disable "rhocp-${MICROSHIFT_VERSION}-for-rhel-${DISTRO_VERSION_MAJOR}-$(uname -i)-rpms"
+            sudo tee /etc/yum.repos.d/microshift-beta.repo > /dev/null <<EOF
+[${microshift_repo}]
+name=MicroShift beta repo
+baseurl=https://mirror.openshift.com/pub/openshift-v4/\$basearch/dependencies/rpms/${MICROSHIFT_VERSION}-el${DISTRO_VERSION_MAJOR}-beta/
+enabled=1
+gpgcheck=1
+skip_if_unavailable=0
+EOF
+            # Import Red Hat public keys to allow RPM GPG check (not necessary if a system is registered)
+            if ! sudo subscription-manager status >& /dev/null ; then
+                sudo rpm --import /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-*
+            fi
+        else
+            microshift_repo="rhocp-${MICROSHIFT_VERSION}-for-rhel-${DISTRO_VERSION_MAJOR}-$(uname -i)-rpms"
+            title "Configuring ${microshift_repo} repo"
+            sudo subscription-manager repos --enable "${microshift_repo}"
+            sudo rm -f /etc/yum.repos.d/microshift-beta.repo
+        fi
+        repos="${repos} ${microshift_repo}"
+
+        sudo subscription-manager repos --enable "fast-datapath-for-rhel-8-$(uname -i)-rpms"
+        repos="${repos} fast-datapath-for-rhel-8-$(uname -i)-rpms"
+        ;;
+
+    *)
+        fatal "\"${DISTRO}\" is not a supported distribution."
+        ;;
+esac
+
+# Sync RPMs to mirror repo
+title "Downloading RPMs into mirror repo"
+for r in ${repos}; do
+    sudo reposync --arch="$(uname -i)" --arch=noarch --gpgcheck --newest-only \
+        --download-path "${MIRROR_DIR}" --repo="${r}"
+done
 
 # Remove coreos packages to avoid conflicts
-find openshift-local -name \*coreos\* -exec rm -f {} \;
-# Exit if no RPM packages were found
-if [ $(find openshift-local -name '*.rpm' | wc -l) -eq 0 ] ; then
-    echo "No RPM packages were found at the 'rhocp-4.11-for-rhel-8-${BUILD_ARCH}-rpms' repository. Exiting..."
-    exit 1
+sudo find "${MIRROR_DIR}" -name \*coreos\* -exec rm -f {} \;
+
+# If we have MicroShift RPMs built from source, add them to the mirror repo.
+if stat -t "${MICROSHIFT_RPM_DIR}"/microshift*.rpm >/dev/null 2>&1; then
+    title "Copying MicroShift RPMs from ${MICROSHIFT_RPM_DIR} into mirror repo."
+    sudo rm -f "${MIRROR_DIR}/${microshift_repo}"/microshift*.rpm
+    sudo cp "${MICROSHIFT_RPM_DIR}"/microshift*.rpm "${MIRROR_DIR}/${microshift_repo}"
 fi
-createrepo openshift-local >/dev/null
 
-title "Mirror Ansible repo"
-# Download openshift local RPM packages (noarch for python and selinux packages)
-rm -rf ansible-local 2>/dev/null || true
-reposync -n -a ${BUILD_ARCH} -a noarch --download-path ansible-local \
-            --repo=ansible-2.9-for-rhel-8-x86_64-rpms >/dev/null
-createrepo ansible-local >/dev/null
+# Create the repo.
+title "Creating the local MicroShift RPM repo"
+sudo createrepo "${MIRROR_DIR}" >/dev/null
 
-title "Done"
-popd &>/dev/null
+# Add the repo as Image Builder source.
+title "Adding the local MicroShift RPM repo as Image Builder source"
+sudo tee "${MIRROR_DIR}/source_microshift-local.toml" > /dev/null <<EOF
+id = "microshift-local"
+name = "Local MicroShift repo"
+type = "yum-baseurl"
+url = "file://${MIRROR_DIR}/"
+check_gpg = false
+check_ssl = false
+system = false
+EOF
+
+sudo composer-cli sources delete "microshift-local" 2>/dev/null || true
+sudo composer-cli sources add "${MIRROR_DIR}/source_microshift-local.toml"
